gsap.to('.one', { duration: 2, delay: 1, x: -400, ease: 'power2.inOut', opacity: 0 })
gsap.from('.two', { duration: 2, delay: 1.2, x: -400, ease: 'power2.inOut', opacity: 0 })
gsap.from('.header', { duration: 2, delay: 2.2, y: 100, opacity: 0 })
gsap.from('.links', { duration: 2, delay: 2.4, y: 100, ease: 'power2.in', opacity: 0 })
gsap.from('.mobile', { duration: 1, delay: 2, y: 100, ease: 'power2.in', opacity: 0 })
gsap.from('h1', { duration: 2, delay: 1.5, x: 100, ease: 'power2.in', opacity: 0 })
gsap.from('.btn', { opacity: 0, delay: 4, duration : 1, rotation: 720 })
